image: toshayo/ubuntu-with-stuff

build-deb:
  stage: build
  variables:
    PACKAGE_NAME: "kbd-and-fan-ctrl"
  script:
    - >-
      echo "Installed-Size: $((($(du -sb rootfs/ | cut -f 1) + 1024) / 1024))" >> rootfs/DEBIAN/control

    # Force file permissions
    - find rootfs -type d -exec chmod 755 {} \;
    - find rootfs -type f -exec chmod 644 {} \;
    - chmod -R 755 rootfs/DEBIAN rootfs/opt/kbd-and-fan-ctrl/start.sh

    - fakeroot dpkg-deb --build rootfs "${PACKAGE_NAME}_${CI_COMMIT_TAG:-${CI_COMMIT_SHORT_SHA}}.deb"
  artifacts:
    paths:
      - ./*.deb
    when: on_success
